"""Bearer-token authentication for the Agent Brain API (Issue #179).

Every router except ``/health`` depends on :func:`verify_bearer_token`. The token
is the server's ``API_KEY`` (auto-generated by ``agent-brain init`` into
``.agent-brain/runtime.json`` at mode 600 and sent by the CLI as
``Authorization: Bearer <token>``).

Design notes:

* ``127.0.0.1`` is not an authorization boundary. On a multi-agent dev box any
  local process can otherwise read or wipe the index (OWASP API1/API2:2023).
* The scheme is ``Authorization: Bearer`` rather than ``X-API-Key`` so it is
  forward-compatible with the MCP v4 OAuth 2.1 work (#188) — one auth scheme
  that evolves from a static key to OAuth-issued bearer tokens.
* Unauthenticated localhost dev is still possible, but only via the explicit
  ``agent-brain-serve --insecure`` opt-out (``INSECURE_NO_AUTH``), never by
  default — the server refuses to start without a key otherwise.
"""

import secrets
from typing import Annotated

from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from agent_brain_server.config.settings import Settings, get_settings

# auto_error=False so a missing/malformed header reaches verify_bearer_token and
# yields a uniform 401 with a WWW-Authenticate hint, rather than FastAPI's
# default 403 for a missing credential.
_bearer_scheme = HTTPBearer(auto_error=False, description="Agent Brain API key")

_UNAUTHENTICATED_HEADERS = {"WWW-Authenticate": "Bearer"}


def verify_bearer_token(
    credentials: Annotated[
        HTTPAuthorizationCredentials | None, Depends(_bearer_scheme)
    ],
    settings: Annotated[Settings, Depends(get_settings)],
) -> None:
    """FastAPI dependency that enforces ``Authorization: Bearer <API_KEY>``.

    Args:
        credentials: Parsed ``Authorization`` header, or ``None`` if absent.
        settings: Application settings (overridable in tests via
            ``app.dependency_overrides[get_settings]``).

    Raises:
        HTTPException: 401 if the header is missing, malformed, or the token does
            not match ``API_KEY``. 503 if auth is required but no key is
            configured (defensive — the server refuses to start in that state
            unless ``--insecure``, so this is unreachable in normal operation but
            fails closed rather than open).
    """
    # Operator explicitly opted out of auth via `agent-brain-serve --insecure`.
    if settings.INSECURE_NO_AUTH:
        return

    api_key = settings.API_KEY.get_secret_value() if settings.API_KEY else None
    if not api_key:
        # Fail closed: auth is on but no key is configured. Unreachable in normal
        # operation (startup refuses this state), but never fall through to open.
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Server authentication is misconfigured (no API key set).",
        )

    if credentials is None or credentials.scheme.lower() != "bearer":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing or malformed Authorization header (expected Bearer).",
            headers=_UNAUTHENTICATED_HEADERS,
        )

    # Constant-time comparison to avoid leaking the key via timing.
    if not secrets.compare_digest(credentials.credentials, api_key):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid API key.",
            headers=_UNAUTHENTICATED_HEADERS,
        )
